CPT: Update `set_node_attributes()` call for `networkx` version 2.0
Upgrade to `networkx` version 2.0 leads to one error during test setup for the
graph-analysis module as well as errors in:
 - fsic.tests.test_build_chain.test_build_chain_sim()
 - fsic.tests.test_build_chain.test_build_chain_re()

The error raised is:

  TypeError: unhashable type: 'dict'

from code like the following:

  nx.set_node_attributes(G, 'equations', equation_mapping)

This is because the function signature changed in version 2.0 of `networkx`
(see
https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html)

Solved with switch to keyword arguments (to uncover the next problem).