CPT: Switch to `InDegreeView` object to check node in-degree
Address next set of errors in:
 - fsic.tests.test_build_chain.test_build_chain_sim()
 - fsic.tests.test_build_chain.test_build_chain_re()

Error:

  AttributeError: 'InDegreeView' object has no attribute 'items'

from call:

  in_degree_zero = sorted([n for n, i in G.in_degree().items()
                           if i == 0])

`DiGraph.in_degree` is now a `dict`-like `DegreeView`, rather than a method
which returns a `dict`.